<?php 
	$productData = $this->productGrid();
	$_product =  Mage::getModel('catalog/product');
?>
	<?php if($productData) : ?>
		<h4 class='text-ms-feature'>Featured MarketSpace Products</h4>
		<?php 
			$i = 0;
			$total_products = count($productData); 
		?>
		<?php foreach($productData as $prod) : ?>
			<?php if($i % 4 == 0 || $i == 0) : ?>
				<div class="row">
			<?php endif; ?>
				<div class="col-xs-6 col-sm-6 col-md-3 ms-featured-item">
					<div class='thumbnail text-center'>
						<?php $_product =  Mage::getModel('catalog/product')->load($prod['product_id']); ?>
						<a href="<?php print $_product->getProductUrl() ?>">
							<img src="<?php print $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(135)?>" />
							<h2 class='text-ms-label product-name'><?php print $_product->getName() ?></h2>
						</a>
					</div>
				</div>
			<?php $i++ ?>
			<?php if(($i % 4 == 0) || $i == $total_products) : ?>
				</div>
			<?php endif; ?>			
		<?php endforeach; ?>
	<?php endif; ?>