<?php

		$productData = Mage::getModel('promotionsmgr/promotionsmgr')->getCollection()
			->addFilter('position','featured')
			->addFilter('status', 1)
			->setOrder('abc', 'ASC')
			->setPageSize(16)
			->getData();
			print "hello";
			print_r($productData);
		
		if(count($productData)>0) {
			$output = "<h1 class='subtitle'><img src='/skin/frontend/default/default/images/es15/headline_featured_marketplace_products.png'></img></h1><ul class='products-grid'>";
			foreach($productData as $prod) {
				$_product =  Mage::getModel('catalog/product');//should use singleton or object reference I think need to experiment
				$currProd = $_product->load($prod['product_id']);
				$output .= "<li class='item'><a class='product-image' href='".$currProd->getProductUrl()."'>";
				$output .= "<img src='".$this->helper('catalog/image')->init($currProd, 'thumbnail')->resize(135)."' ></img></a>";
				$output .= "<a href='".$currProd->getProductUrl()."'<h2 class='product-name'>".$currProd->getName()."</h2></a></li>";
			}
			$output .= "</ul>";
			print $output;
		}	     