<?php
	if($_category  = Mage::registry('current_category')) {
		$images = $this->getImageRotatorImages(array('category_id' => $_category->getId()));
	} else {
		$images = $this->getImageRotatorImages(array('category_id' => 1));
	}
?>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
  	<?php for($i = 0; $i < count($images); $i++) : ?>
    	<li data-target="#carousel-example-generic" data-slide-to="<?php print $i; ?>" <?php $i == 0 ? print 'class="active"' : '' ?>></li>
    <?php endfor; ?>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
  	<?php for($i = 0; $i < count($images); $i++) : ?>
	    <div class="item<?php $i == 0 ? print ' active' : '' ?>"> <!-- I think active class causes the image slider to bump up on rotate -->
	      <?php if(!empty($images[$i]['link'])) : ?>
	      	<a href="<?php print $images[$i]['link']; ?>">
	      <?php endif; ?>
	      
	      <img class="img-responsive" width="100%" src="<?php echo Mage::getBaseUrl('media') . DS . "promotions" . DS . $images[$i]['image_url'] ?>" 
	      	alt="<?php !empty($images[$i]['image_alt_tag']) ? print $images[$i]['image_alt_tag'] : print 'community marketspace'; ?>"></a>
	      
	      <?php if(!empty($images[$i]['link'])) : ?>
	      	</a>
	      <?php endif; ?>
	    </div>
    <?php endfor; ?>									    												    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>                					
</div>