<?php
	if($_category  = Mage::registry('current_category')) {
		$images = $this->getAdImagesByPosition(array('category_id' => $_category->getId(), 'limit' => 30)); //used to be $this->ads_count
	} else {
		$images = $this->getAdImagesByPosition(array('category_id' => 1, 'limit' => 30));
	}
?>
<?php if($images) : ?>
	<?php $count_images = count($images); ?>
	<?php for($i = 0; $i < $count_images; $i++) : ?>
	  <?php if(!empty($images[$i]['link'])) : ?>
	  	<a target="_blank" href="<?php print $images[$i]['link']; ?>">
	  <?php endif; ?>
	   <img class="img-responsive ms-right-sidbar-image" src="<?php echo Mage::getBaseUrl('media') . DS . "promotions" . DS . $images[$i]['image_url'] ?>" 
	  	  alt="<?php !empty($images[$i]['image_alt_tag']) ? print $images[$i]['image_alt_tag'] : print 'community marketspace'; ?>"></a>
	  
	  <?php if(!empty($images[$i]['link'])) : ?>
	  	</a>
	  <?php endif; ?>
	<?php endfor; ?>
<?php endif; ?>