<div class="row text-center ms-social-row">
  <div class="text-center">
    <a target="_blank" href="https://www.facebook.com/communitymarketspace" type="button" class="btn ms-no-left-right-pad">
      <img class="ms-social-btn img-responsive" src="/skin/frontend/default/default/images/ms/SI_Facebook.png" />
    </a>
  </div>
</div>
<div class="row text-center ms-social-row">
  <div class="text-center">
    <a target="_blank" href="https://twitter.com/BoldlyLocal" type="button" class="btn ms-no-left-right-pad">
      <img class="ms-social-btn img-responsive" src="/skin/frontend/default/default/images/ms/Twitterimages.png" />
    </a>
  </div>
</div>