<div id="search_input" class="input-group input-lg m-t">
  <input type="text" name="q" id="q" autocomplete="off" spellcheck="false" autocorrect="false" class="form-control input-lg string" placeholder="Search by name, category etc"/>
  <span class="input-group-addon"><i id="input-loop" class="glyphicon glyphicon-search"></i></span>
</div>

<div class="row">

  <!-- Left Column -->
  <div class="col-md-3 col-md-offset-1 col-xs-12 hidden-sm hidden-xs">
    <div class="main_caption">
      <p class="main-caption_text"></p>
    </div>
    <!-- Facets -->
    <div id="facets" class="hidden-sm hidden-xs"></div>
  </div>
  <!-- /Left Column -->

  <!-- Right Column -->
  <div class="col-md-7 col-xs-12">

    <!-- Stats + sort order menu -->
    <div class="page-header">
      <div class="pull-right sort-orders">
        <span id="sort-by" class="text-muted">Sort by:</span>
        <div class="btn-group">
          <button id="sort-button" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="sort-by">Relevance</span> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#" class="sortBy" data-index-suffix="">Relevance</a></li>
            <li><a href="#" class="sortBy" data-index-suffix="_price_asc">Lowest Price</a></li>
            <li><a href="#" class="sortBy" data-index-suffix="_price_desc">Highest Price</a></li>
          </ul>
        </div>
      </div>
      <span id="stats"></span>
      <div style="clear:both;"></div>
    </div>
    <!-- /Stats + sort order menu -->

    <!-- Hits -->
    <div id="hits"></div>
    <!-- /Hits -->

    <!-- Pagination -->
    <div id="pagination"></div>
    <!-- /Pagination -->

    <!-- /Right Column -->
  </div>
</div>

<!-- Facet template -->
<script type="text/template" id="facet-template">
  <div class="facet">
    <!-- facet title -->
    <div class="page-header">
      <h5>{{ title }}</h5>
    </div>
    <ul class="list-unstyled">

      {{#values}}
      <li class="{{#refined}}refined{{/refined}}">
        {{#disjunctive}}
        <input class="checkbox toggleRefine" data-facet="{{ facet }}" data-value="{{ value }}" type="checkbox" {{#refined}}checked="checked"{{/refined}}>
        {{/disjunctive}}
        <a class="facet_link toggleRefine" data-facet="{{ facet }}" data-value="{{ value }}" href="#">{{ label }}</a>
        <small class="facet_count text-muted pull-right">{{ count }}</small>
      </li>
      {{/values}}

      <!-- other values will only be displayed if the use click on the "show more" link  -->
      {{#has_other_values}}
      <!-- "show more" link -->
      <li class="show-more"><a href="#"><i class="glyphicon glyphicon-chevron-down" /> more</a></li>

      <!-- other values -->
      {{#other_values}}
      <li class="{{#refined}}refined{{/refined}} additional-facets show-more">
        {{#disjunctive}}
        <input class="checkbox toggleRefine" data-facet="{{ facet }}" data-value="{{ value }}" type="checkbox" {{#refined}}checked="checked"{{/refined}}>
        {{/disjunctive}}
        <a class="facet_link toggleRefine" data-facet="{{ facet }}" data-value="{{ value }}" href="#">{{ label }}</a><small class="text-muted pull-right">{{ count }}</small>
      </li>
      {{/other_values}}

      <!-- "show less" link -->
      <li class="show-less"><a href="#"><i class="glyphicon glyphicon-chevron-up" /> less</a></li>
      {{/has_other_values}}
    </ul>
  </div>
</script>

<!-- Slider template -->
<script type="text/template" id="slider-template">
  <div class="facet">
    <ul class="list-unstyled">
      <div class="page-header">
        <h5>{{ title }}</h5>
      </div>
      <li class="facet-slider">
        <b>{{ min }}</b>
        <input type="text" data-slider-min="{{ min }}" data-slider-max="{{ max }}" data-slider-step="1" data-slider-value="[{{ values }}]" data-slider-orientation="horizontal" data-slider-selection="after" id="{{ facet }}-slider" />
        <b>{{ max }}</b>
      </li>
    </ul>
  </div>
</script>

<!-- Hit template -->
<script type="text/template" id="hit-template">
  <div class="hit media">
    <a class="pull-left" href="{{ url }}">
      <img class="media-object" src="{{ image }}" alt="{{ name }}">
    </a>
    <div class="media-body">
      <h3 class="hit_price pull-right text-right text-danger">
        ${{ salePrice }}
      </h3>
      <h4 class="hit_name">{{{ _highlightResult.name.value }}}</h4>
      <p>
        {{{ _highlightResult.shortDescription.value }}}
      </p>
      <ul class="hit_tags list-inline">
        {{#_highlightResult.manufacturer}}<li>{{{ _highlightResult.manufacturer.value }}}</li>{{/_highlightResult.manufacturer}}
        {{#_highlightResult.category}}<li>{{{ _highlightResult.category.value }}}</li>{{/_highlightResult.category}}
        {{#type}}<li>{{{ type }}}</li>{{/type}}
        <!-- TODO TODO Use Bootstrap labels here -->
      </ul>
    </div>
  </div>
</script>

<!-- Pagination template -->
<script type="text/template" id="pagination-template">
  <div class="text-center">
    <ul class="pagination">
      <li {{^prev_page}}class="disabled"{{/prev_page}}><a href="#" {{#prev_page}} class="gotoPage" data-page="{{ prev_page }}" {{/prev_page}}>&#60;</a></li>
      {{#pages}}
      <li class="{{#current}}active{{/current}}{{#disabled}}disabled{{/disabled}}"><a href="#" {{^disabled}} class="gotoPage" data-page="{{ number }}" {{/disabled}}>{{ number }}</a></li>
      {{/pages}}
      <li {{^next_page}}class="disabled"{{/next_page}}><a href="#" {{#next_page}} class="gotoPage" data-page="{{ next_page }}" {{/next_page}}>&#62;</a></li>
    </ul>
  </div>
</script>

<!-- Stats template -->
<script type="text/template" id="stats-template">
  <h5>{{ nbHits }} RESULT{{#nbHits_plural}}S{{/nbHits_plural}} <span class="text-muted hidden-sm hidden-xs">Found in {{ processingTimeMS }}ms</span></h5>
</script>