<?php
/* @var $this MS_Template_Block_Category */
/* @var $category Mage_Catalog_Model_Category */
$category = $this->_category;
?>
<?php if($category->hasChildren()) : ?>
    <?php
        /* @var $collection Mage_Catalog_Model_Resource_Category_Collection */
        $collection = $this->GetChildrenForNavigationLinks($category);
    ?>
        <?php $i = 0; ?>
        <?php $total = $collection->count(); ?>
        <?php foreach($collection as $key => $cat) : ?>
            <?php if($i % 9 == 0) : ?>
                <div class="row">
            <?php endif; ?>
            <?php if($i % 1 == 0) : ?>
                <div class="col-md-4 col-sm-6 col-xs-6">
                    <ul class="nav nav-stacked">
            <?php endif; ?>
            <li>
                <a class="ms-green-text" href="/<?php print $cat['url_path']; ?>">
                    <?php print $cat['name']; ?>
                </a>
            </li>
        <?php $i++; ?>
        <?php if($i % 1 == 0 || (($i + 1) > $total)) : ?>
                </ul>
            </div>
        <?php endif; ?>
        <?php if($i % 9 == 0 || (($i + 1) > $total)) : ?>
            </div>
        <?php endif; ?>
        <?php endforeach; ?>
<?php endif; ?>