<!--<nav class="headerTopLinks navbar">-->
<!--	<div class="collapse navbar-collapse">-->
<!--		<ul class="nav navbar-nav">-->
<!--			<li class="topLink active"><a href="/">HOME</a></li>-->
<!--			<li class="topLink"><a href="--><?php //print Mage::getBaseUrl() ?><!--customer/account">MY ACCOUNT</a></li>-->
<!--			<li class="topLink"><a href="--><?php //print Mage::getBaseUrl() ?><!--checkout/cart">SHOPPING CART</a></li>-->
<!--			--><?php //if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
<!--				<li class="topLink"><a href="--><?php //echo Mage::helper('customer')->getLoginUrl(); ?><!--">LOGIN</a></li>-->
<!--			--><?php //else: ?>
<!--				<li class="topLink"><a href="--><?php //echo Mage::helper('customer')->getLogoutUrl(); ?><!--">LOGOUT</a></li>-->
<!--			--><?php //endif; ?>
<!--			<!--<li>--><?php //echo $this->getChildHtml('topSearch') ?><!--</li>-->
<!--		</ul>-->
<!--	</div>-->
<!--</nav>-->

<nav class=" headerTopLinks navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#vl-top-nav-dropdown">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand"
         href="<?php echo str_replace("index.php/", "", $this->getUrl('')); ?>"
         title="<?php echo $this->getLogoAlt() ?>">
        <img class="img-responsive" width="250px"
             src="<?php echo $this->getSkinUrl('images/vl/wel-wordmark-green.png'); //$this->getLogoSrc() ?>"
             alt="<?php echo $this->getLogoAlt() ?>"
        />
      </a>
    </div>

    <div class="collapse navbar-collapse" id="vl-top-nav-dropdown">
      <ul class="nav navbar-nav pull-left">
        <li class="topLink btn"><a href="<?php print Mage::getBaseUrl() ?>about-community-marketspace">ABOUT</a></li>
        <li class="topLink btn"><a href="<?php print Mage::getBaseUrl() ?>customer/account">MY ACCOUNT</a></li>
        <li class="topLink btn"><a href="<?php print Mage::getBaseUrl() ?>checkout/cart">SHOPPING CART</a></li>
        <?php if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
          <li class="topLink btn"><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>">LOGIN</a></li>
        <?php else: ?>
          <li class="topLink btn"><a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">LOGOUT</a></li>
        <?php endif; ?>
      </ul>
<!--      --><?php //echo $this->getChildHtml('topSearch'); ?>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

