<?php
$products = $this->getProductsByMarketspaceOwnerId($this->getOwnerId());
?>
<?php $i = 0; ?>
<?php if (count($products) > 0) : ?>
	<div class="row">
		<?php foreach($products as $key => $product) : ?>
            <?php
                $show_deals = false;
                if(in_array($product['product_type'], array(8, 9))) {
                    $show_deals = true;
                } else {
                    $show_deals = false;
                }
            ?>
			<?php if($i % 4 == 0) : ?>
				<div class="row">
			<?php endif; ?>
				<div class="col-xs-12 col-sm-3 col-md-3 ms-featured-item">
					<div class='thumbnail text-center'>
                        <a class="product-image" href="<?php print $product->getProductUrl() ?>">
                            <img src="<?php print $this->helper('catalog/image')->init($product, 'thumbnail')->resize(135)?>" />
                        </a>
                        <a href="<?php print $product->getProductUrl() ?>">
                            <h2 class='text-ms-label product-name'>
                                <?php print $product->getName() ?>
                            </h2>
                        </a>
                        <?php if($show_deals) : ?>
                            <img class="pull-left" src="<?php print $this->getSkinUrl('css/images/CM_DEAL.png') ?>" />
                        <?php endif; ?>
					</div>
				</div>
			<?php $i++ ?>
			<?php if($i % 4 == 0) : ?>
				</div>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
<?php endif; ?>