<?php
$products = $this->getProductsByMarketspaceOwnerId($this->getOwnerId());
?>
<?php $i = 0; ?>
<?php if (count($products) > 0) : ?>
	<div class="row">
		<?php foreach($products as $key => $product) : ?>
			<?php if($i % 4 == 0) : ?>
				<div class="row">
			<?php endif; ?>
				<div class="col-xs-12 col-sm-3 col-md-3 ms-featured-item">
					<div class='thumbnail'>
					  <a class="product-image" href="<?php print $product->getProductUrl() ?>">
						<img src="<?php print $this->helper('catalog/image')->init($product, 'thumbnail')->resize(135)?>" /></a>
						<a href="<?php print $product->getProductUrl() ?>"<h2 class='text-ms-label product-name'><?php print $product->getName() ?>"</h2></a>
					</div>
				</div>
			<?php $i++ ?>
			<?php if($i % 4 == 0) : ?>
				</div>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
<?php endif; ?>