  <style> 
  p { color:red; margin:5px; cursor:pointer; } 
  p.hilite { background:yellow; } 
  #orderSummary th, td {font-weight:bold;}
  </style> 

<script type="text/javascript">

jQuery(document).ready(function() {
	var d = new Date();
	var curr_date = d.getDate();
	//$('input[name="x_exp_date"]').css("border","red 3px solid");
	jQuery('input[name="x_exp_date"]').datepick({minDate: curr_date, dateFormat: 'mm/yy', showTrigger: '<img id="calImg" style="cursor:pointer;width:25px;height:25px;" src="http://escapelocally.com/skin/frontend/default/default/images/date_picker.jpg" />'});

    jQuery("#ccvhelp").hover(function () { 
      jQuery(this).prepend("<div style='width:100px;height:20px;background:white;z-index:10;position:relative;top:20px;left:20px;' id='ccvtip'>this is the</span>");
    }, function () { 
      jQuery("#ccvtip").remove(); 
    }); 

});


</script>

<?php require_once 'anet_php_sdk/AuthorizeNet.php'; // The SDK
if(isset($_POST['orderAmt'])) {
//$url = "http://www.escapelocally.com/purchase/index/response";
$api_login_id = '522LbKuKU'; //'3B6hVAx7p'; //
$transaction_key = '5FsHc24t2GZt2w6D'; //'7su8KfBZ83M62afw'; //
$amount = $_POST['orderAmt'];
$fp_sequence = $_POST['orderNum'];
$orderId = $_POST['orderId'];

$orderObj = Mage::getModel('sales/order')->loadByIncrementId($orderId); 
$orderEntityId = $orderObj->getId();
$order = Mage::getModel('sales/order_Address')->getCollection()->addAttributeToFilter('parent_id',$orderEntityId)->getFirstItem();
$regionId = $order->getRegionId();
$regionModel = Mage::getModel('directory/region')->load($regionId);
$regionCode = $regionModel->getCode();
$md5_setting = '3e64fb030074ed8c5ab8'; // Any sequential number like an invoice number.
$relay_response_url = "http://escapelocally.com/formprocess?orderId=".$orderId; // You will create this file in See Create relay_response.php...
echo "<p style='font-size:16px;'>Please confirm your order price and fill out this form to purchase your experience.<br /><b> Order Price:</b> " . number_format($amount, 2);
echo AuthorizeNetDPM::getCreditCardForm($amount, $fp_sequence, $relay_response_url,$api_login_id,$transaction_key,false,true,$order, $regionCode);
//AuthorizeNetDPM::directPostDemo($relay_response_url, $api_login_id, $transaction_key, $amount, $md5_setting);
} elseif(isset($_GET['orderId'])) {
$redirect_url = "http://escapelocally.com/purchase";
// Where the user will end up.
$api_login_id = '522LbKuKU'; //'3B6hVAx7p';  //
$md5_setting = "3e64fb030074ed8c5ab8"; // Your MD5 Setting
$response = new AuthorizeNetSIM($api_login_id, $md5_setting);
$transaction_id = $_GET['orderId'];
if ($response->isAuthorizeNet())
{
  if ($response->approved)
  {
echo AuthorizeNetDPM::getRelayResponseSnippet($redirect_url);
  // Do your processing here.
  $orderId = $_GET['orderId'];
  $redirect_url .= '?response_code=1&transaction_id='.$transaction_id;// .$response->transaction_id;
  $_order = Mage::getModel('sales/order')->loadByIncrementId($orderId);
  if($_order->canInvoice()) {
	/**
	 * Create invoice
	 * The invoice will be in 'Pending' state
         * Need to prepare invoice ($order object) then register (invoice object)
	 */
	//$invoiceId = Mage::getModel('sales/order_invoice_api')->create($_order->getIncrementId(), array(),"",true,true);
 
	//$invoice = Mage::getModel('sales/order_invoice')->loadByIncrementId($invoiceId);
        
	/**
	 * Pay invoice
	 * i.e. the invoice state is now changed to 'Paid'
	 */
        //$invoice->register();
        //$invoice->setEmailSent(true);
        //$invoice->sendEmail();
	//$invoice->capture()->save();
        
    }
  }
  else
  {
  $redirect_url .= '?response_code='.$response->response_code . '&response_reason_text=' . $response->response_reason_text;
  }
// Send the Javascript back to AuthorizeNet, which will redirect user back to your site.


}
}elseif(isset($_GET['transaction_id']))
{
echo "Thank you for your order. You will recieve an email shortly confirming your payment.<br />";
$orderId = $_GET['orderId2'];
echo "Your order number is: ". $orderId . "<br />";

$_order = Mage::getModel('sales/order')->loadByIncrementId($orderId);
//echo $_order->getIncrementId();
//echo "status: " . $_order->getStatus() . "<br />";
//echo "state: " . $_order->getState();
//$_order->setStatus("processing");
//$_order->setState("processing");
//$_order->save();
//echo "<br /> Status New: " . $_order->getStatus();
//echo "<br /> State New: " . $_order->getState();

$items = $_order->getAllItems();

echo "The email has been sent to: ". $_order->getCustomerEmail() . "<br /><b>Order Summary</b><br />";
echo "<table id='orderSummary' width='100%'><thead><tr style='background:white;border:1px solid black;padding:5px;font-weight:bold;font-size:18px;'><th width='40%'>Name</th><th>Quantity</th><th>Amount</th></tr><tbody>";
foreach($items as $item) {
$itemData = $item->getData();
echo "<tr style='padding:5px;'><td>".$item->getName()."</td><td>".$itemData['qty_ordered']."</td><td>".$item->getPrice()."</td></tr>";
//var_dump(get_object_vars($item));
print_r($item->getCustomOptions());
}
echo "</tbody></table>";
//$_order->sendNewOrderEmail(false);
if($_order->canInvoice()) {
	/**
	 * Create invoice
	 * The invoice will be in 'Pending' state
         * Need to prepare invoice ($order object) then register (invoice object)
	 */
//echo " got this far";
	$invoiceId = Mage::getModel('sales/order_invoice_api')->create($_order->getIncrementId(), array(),"",true,false);
        //$invoice = Mage::getModel('sales/order_invoice')->loadByIncrementId($invoiceId);
        //$invoice->register();
        //$_order->setStatus("complete");
        //$_order->setState("complete");
        //$invoice->sendUpdateEmail();
        $_order->sendNewOrderEmail(false);
	//$invoice->capture()->save();
   }
} elseif(isset($_GET['response_code'])) {
echo "<span style='font-size:14px'>Your order could not be completed for the following reason:</span><br /><p style='color:red;font-weight:bolder;'> " . $_GET['response_reason_text'] . "</p>";

} else {
header( 'Location: http://www.escapelocally.com/customer/account' );
}

?>

